x-db-path: &db-path
  DL_SENSOR: misc_0
  DL_STATUS: misc_1
  DB_URI: ws://graph:5432/rpc
  DB_FILE: app.db
  DATA_PATH: /appdata/

services:
  distrilock:
    container_name: dl
    build:
      context: ./services/distrilock
      dockerfile: distrilock.dockerfile
    volumes:
      - ./services/distrilock:/app
      - /dev/shm/dpmem:/mem
    restart: unless-stopped
    command: python3 -OO server.py mem

  graph:
    container_name: graph
    image: surrealdb/surrealdb:latest
    ports: # NOTE do not open firewall for this port
      - 5432:5432
    # expose:
    # - 5432
    volumes:
      - ./appdata:/appdata
    restart: unless-stopped
    command: start file:/appdata/app.db --bind 0.0.0.0:5432 --log error # --allow-scripting

  mqtt_auth_service: # Both this and container_name works as hostname
    depends_on:
      - graph
    container_name: mas
    build:
      context: ./services/mqtt_auth_service
      dockerfile: mqtt_auth_service.dockerfile
    volumes:
      - ./services/mqtt_auth_service:/app
      - ./certs/mqtt:/certs/mqtt:ro
      - ./certs/ca:/certs/ca:ro
      - ./appdata:/appdata
    ports:
      - 8888:8888
    environment:
      <<: *db-path
    restart: unless-stopped
    command: python3 -OO main.py

  api:
    depends_on:
      - graph
      - distrilock
    container_name: api
    build:
      context: ./services/api
      dockerfile: api.dockerfile
    volumes:
      - /dev/shm/dpmem:/mem
      - ./services/api:/app
      - ./certs/api:/certs/api:ro
      - ./certs/ca:/certs/ca:ro
      - ./appdata:/appdata
    ports:
      - 8000:8000
    environment:
      REFRESH_JWT_DAYS: 180
      ACCESS_JWT_MINUTES: 15
      <<: *db-path
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: sh start.sh 8000

  mqtt:
    container_name: mqtt
    build:
      context: ./services/mqtt
      dockerfile: Dockerfile
    volumes:
      - ./services/mqtt/mosquitto.cfg:/etc/mosquitto/mosquitto.conf:ro
      - ./services/mqtt/go-auth.cfg:/etc/mosquitto/conf.d/go-auth.conf:ro
      - ./certs/ca/root.crt:/usr/local/share/ca-certificates/myroot.crt:ro
      - ./certs/mqtt:/certs/mqtt:ro
    logging:
      driver: none
    ports:
      - 8883:8883
      - 9001:9001
    # environment:
    #   REDIS_DB: 0 # symbolic value, to be changed in go-auth.cfg
    restart: unless-stopped

  sensor_listener:
    depends_on:
      - mqtt
      - distrilock
    container_name: sli
    build:
      context: ./services/sensor_listener
      dockerfile: sensor_listener.dockerfile
    environment:
      <<: *db-path
    volumes:
      - ./certs/sensor_listener:/certs/sensor_listener:ro
      - ./services/sensor_listener:/app
      - ./appdata:/appdata
      - ./certs/ca:/certs/ca:ro
      - /dev/shm/dpmem:/mem
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: python3 -OO main.py

  ddns:
    container_name: ddns
    build: ./services/ddns
    environment:
      <<: *db-path
    volumes:
      - ./appdata:/appdata:ro
    logging:
      driver: none
    restart: unless-stopped
    network_mode: host

  ntp_server:
    container_name: ntp_server
    build: ./services/ntp_server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 123:123/udp
    restart: unless-stopped
