#!/bin/bash

# The IP for the server you wish to ping. I suggest an internal gateway.
SERVER=192.168.1.1

# Only send two pings, sending output to /dev/null
ping -c2 ${SERVER} >/dev/null

# If the return code from ping ($?) is not 0 (meaning there was an error)
if [ $? != 0 ]; then
    # Restart the wireless interface
    ip link set wlan0 down
    sleep 5
    ip link set wlan0 up
fi

## Todo add

/usr/local/bin/wifi_rebooter.sh

chmod +x /usr/local/bin/wifi_rebooter.sh

/etc/crontab

*/10 * * * * root /usr/local/bin/wifi_rebooter.sh

systemctl restart cron
